FROM node:alpine

LABEL version="1.9.21"
LABEL description="DreamMerchant Marketing App"
LABEL maintainer = ["ml@michaellogic.com"]

WORKDIR /src

COPY ["package.json", "./"]

RUN npm install --production

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]